# Generated by Django 5.2.12 on 2026-08-17 13:22

from django.db import migrations


def approve_all_owners(apps, schema_editor):
    """Approve all owner profiles and grant them full admin rights."""
    Profile = apps.get_model('products', 'Profile')
    User = apps.get_model('auth', 'User')

    owner_profiles = Profile.objects.filter(role='owner')
    for profile in owner_profiles:
        profile.is_approved = True
        profile.is_primary_owner = True
        profile.is_platform_admin = True
        profile.save()

        # Also grant Django superuser + staff to the linked user
        try:
            user = User.objects.get(pk=profile.user_id)
            user.is_staff = True
            user.is_superuser = True
            user.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_customdepartment_custom_schema_and_more'),
    ]

    operations = [
        migrations.RunPython(approve_all_owners, migrations.RunPython.noop),
    ]
